name: guess_who
description: Guess Who Game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk_flutter: ^5.1.0
  package_info_plus: ^3.0.3
  json_annotation: ^4.8.1
  provider: ^6.0.0
  model_viewer_plus: ^1.5.0
  perfect_volume_control: ^1.0.5
  flag: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/models/